[workspace]
members = ["crates/repomap-core", "crates/repomap"]
resolver = "2"

[workspace.package]
version = "1.2.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/SylphxAI/repomap"
homepage = "https://sylphxai.github.io/repomap/"

[profile.release]
lto = "thin"
codegen-units = 4
strip = true
opt-level = 3
