// One source for public copy. `bun scripts/copy.ts --write` syncs, `--check` verifies (CI).
//  - brand.json "oneliner" -> README lead, docs hero tagline, package.json, server.json
//    (and, with --github, the GitHub repository description)
//  - `repomap tools` -> the README tool table (REPOMAP_BIN or target/release/repomap)
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";

const mode = process.argv.includes("--write") ? "write" : "check";
const github = process.argv.includes("--github");
const { oneliner } = JSON.parse(readFileSync("brand.json", "utf8"));
if (oneliner.length > 100) throw new Error(`oneliner is ${oneliner.length} chars; the MCP Registry allows 100`);
const problems: string[] = [];

function sync(path: string, update: (s: string) => string) {
  const before = readFileSync(path, "utf8");
  const after = update(before);
  if (after === before) return;
  if (mode === "write") writeFileSync(path, after);
  else problems.push(`${path} is out of date`);
}
const json = (field: string) => (s: string) => {
  const o = JSON.parse(s);
  o[field] = oneliner;
  return JSON.stringify(o, null, 2) + "\n";
};
const between = (start: string, end: string, body: string) => (s: string) => {
  const a = s.indexOf(start), b = s.indexOf(end);
  if (a < 0 || b < a) throw new Error(`markers ${start} … ${end} missing`);
  return s.slice(0, a + start.length) + body + s.slice(b);
};

sync("packages/repomap/package.json", json("description"));
sync("server.json", json("description"));
sync("README.md", between("<!-- oneliner -->", "<!-- /oneliner -->", `**${oneliner}**`));
sync("docs/index.md", (s) => s.replace(/^  tagline: .*$/m, `  tagline: ${JSON.stringify(oneliner)}`));

const bin = process.env.REPOMAP_BIN ?? ["target/release/repomap", "target/debug/repomap"].find(existsSync);
if (bin) {
  const table = execFileSync(bin, ["tools"], { encoding: "utf8" });
  sync("README.md", between("<!-- tools:start (generated by `repomap tools`; CI checks it) -->\n", "<!-- tools:end -->", table));
} else if (mode === "check") {
  problems.push("no repomap binary to check the README tool table (set REPOMAP_BIN)");
}

if (github) {
  const desc = execFileSync("gh", ["api", "repos/SylphxAI/repomap", "--jq", ".description"], { encoding: "utf8" }).trim();
  if (desc !== oneliner) {
    if (mode === "write") execFileSync("gh", ["repo", "edit", "SylphxAI/repomap", "--description", oneliner]);
    else problems.push(`GitHub description differs: "${desc}"`);
  }
}

if (problems.length) {
  console.error(`public copy is out of sync with brand.json / the tool registry:\n  ${problems.join("\n  ")}\nRun: bun scripts/copy.ts --write`);
  process.exit(1);
}
console.log(mode === "write" ? "copy synced" : "copy in sync");
